# /hosts/desktop/hardware-configuration.nix
# This file should be generated by nixos-generate-config, but for this example
# we're creating a placeholder. In a real system, run nixos-generate-config
# on the target machine to generate the correct hardware configuration.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Placeholder for desktop hardware configuration
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Blacklist nouveau driver to prevent conflicts with NVIDIA proprietary driver
  boot.blacklistedKernelModules = [ "nouveau" ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  networking.useDHCP = lib.mkDefault true;

  # CPU
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}